sonar.projectKey=Amine3869_tp_elamraoui_amine_sonarcloud
sonar.organization=amine3869


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=tp_elamraoui_amine_sonarcloud
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
